CREATE TABLE reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    study_instance_uid VARCHAR(64) NOT NULL,
    author_id TEXT NOT NULL,
    author_display_name TEXT NOT NULL,
    status VARCHAR(16) NOT NULL,
    content TEXT NOT NULL,
    version BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    finalized_at TIMESTAMPTZ NULL,
    CONSTRAINT uq_reports_study_instance_uid UNIQUE (study_instance_uid),
    CONSTRAINT ck_reports_status CHECK (status IN ('DRAFT', 'FINAL')),
    CONSTRAINT ck_reports_content_length CHECK (char_length(content) BETWEEN 1 AND 32000),
    CONSTRAINT ck_reports_finalized_at CHECK (
        (status = 'DRAFT' AND finalized_at IS NULL) OR
        (status = 'FINAL' AND finalized_at IS NOT NULL)
    )
);
